### PR TITLE
More test and improvements - fix issues with icons in maya dock.

### PR DESCRIPTION
**Pull request by gpijat**
Hey @huntfx,

I've recently released my project (only the framework for now) but I've been working on the UI as well and I have some changes to propose for your package. Feel free to discuss them :)

- Replace `pymel` with `maya.cmds`: Even if I understand the qualities for pymel, it's not something most people want to work with, it's slow to import and not native, I never worked anywhere where it was used or even tolerated. So to improve the accessibility for `vfxwindow` I think we can safely replace it with the default `maya.cmds`, I kept the namespace `mc` you were already using. I've been testing this almost since my last PR and it seems to work the same, except it's faster to launch.
- Minor change on MayaWindow, I've added support last time for the icon on the floating window and it was working well when the windows start as docked. Unfortunately, if the windows is `dockable` but not `docked`, it was displayed with no icon. This is now fixed.
- Replace the numerous dcc names attributes on the AbstractWindow with an "abstract" property to be implemented on subclass to get the name of the software. It's a "nice name" by default but can be tested using `self.software.lower() == 'maya'` to prevent false positive. The best solution is still to do:
```py
from vfxwindow import software

if software.isMaya(): 
    ...
```

Let me know what you think,

Greg.

### CODE REVIEW

**Comment by huntfx** [comment]
Hey again,
It was so long ago that I'd honestly forgotten it was using pymel, but yes I'd be very happy phasing it out lol. I'll have a check of its source code to make sure it's not doing anything extra in regards to docking.
One thing I see you removed was the `qtObj = pm.uitypes.toQtObject(windowID)` part, which was _something_ to do with attaching Maya UIs to a Qt window. Not very important at all, but I should ideally figure that bit out again, and if anything I'll just do a lazy import if it's pymel only.

The software attributes were actually part of the plan to redo when doing a 2.0 version, I'd not decided how best to handle it but I like your idea. I'm definitely up using that going forward, but for the sake of compatibility while it's on 1.x would you be able to restore the attributes back?

Cheers again :)

**Comment by gpijat** [comment]
> Hey again, It was so long ago that I'd honestly forgotten it was using pymel, but yes I'd be very happy phasing it out lol. I'll have a check of its source code to make sure it's not doing anything extra in regards to docking. One thing I see you removed was the `qtObj = pm.uitypes.toQtObject(windowID)` part, which was _something_ to do with attaching Maya UIs to a Qt window. Not very important at all, but I should ideally figure that bit out again, and if anything I'll just do a lazy import if it's pymel only.
> 
> The software attributes were actually part of the plan to redo when doing a 2.0 version, I'd not decided how best to handle it but I like your idea. I'm definitely up using that going forward, but for the sake of compatibility while it's on 1.x would you be able to restore the attributes back?
> 
> Cheers again :)

About the `pm.uitypes.toQtObject(windowID)` I remember doing test to wrap a maya widget (Node Editor, Attribute Editor) and it was working also without this part of the code, it looks like the find control handle it well, at least in Maya 2023 (I'll double check that to be sure 👍)

Oh cool for the attributes, to be honest I was not a fan having all those attributes where most of them shouldn't be on the class so that's the reason for the change, I was also thinking about building classes to represent each software, where we could also be able to get the versions and other things like that but that could've requested way more development and the need is not there yet so that's probably overthinking. I wanted to keep it simple but still clean to use.
But actually you're right, I will bring them back and mark them as deprecated so you know you can remove them on the next major release. (If you want too).

**Comment by gpijat** [comment]
@huntfx It should be better now, we have all attributes for backward compatibility, marked as deprecated since this release name (1.9.0).
It should be compatible to show in sphinx if someday you want to generate a documentation. :)

**Comment by huntfx** [comment]
The attributes are back from when there was only Maya and Nuke support, and I just needed a way of determining which one for the purpose of adding callbacks. It obviously got a lot less "nice" as more software was added lol, but I'd already pushed it to pypi so didn't want to break anything.

> I was also thinking about building classes to represent each software, where we could also be able to get the versions and other things like that but that could've requested way more development and the need is not there yet so that's probably overthinking

I like the sound of that to be honest - just brainstorming here with the basics, but I'm thinking of doing something like this:
```python
# software.py
class NukeSoftware: ...
Nuke = NukeSoftware()  # I'm aware it would be more pythonic as NUKE but I find it looks a bit ugly with Qt

# init.py
from vfxwindow import software
if software.Nuke:  # Using bool will determine if it's the current software
    from .nuke import NukeWindow as VFXWindow

# nuke.py
>>> from vfxwindow.software import Nuke
>>> self.software = Nuke
>>> self.software
'Nuke'
>>> self.software == 'nuke'  # case insensitive check
True
>>> self.software.batch  # hide away the batch mode attribute
False
>>> self.software.version  # gets the full version as a string
'14.0v5'
>>> int(self.software.version)  # gets the major version
14
>>> float(self.software.version)  # gets the major and minor version
14.0
```

Also thanks, I've never quite known how to properly deprecate stuff. Since I'm using 2.0 as an excuse to do a major code cleanup, I'm planning on expanding the documentation a lot more then as I do that :)

(also don't worry about testing the Maya widget wrapping, I'll get round to doing it at some point)

**Comment by gpijat** [comment]
> The attributes are back from when there was only Maya and Nuke support, and I just needed a way of determining which one for the purpose of adding callbacks. It obviously got a lot less "nice" as more software was added lol, but I'd already pushed it to pypi so didn't want to break anything.
> 
> > I was also thinking about building classes to represent each software, where we could also be able to get the versions and other things like that but that could've requested way more development and the need is not there yet so that's probably overthinking
> 
> I like the sound of that to be honest - just brainstorming here with the basics, but I'm thinking of doing something like this:
> 
> ```python
> # software.py
> class NukeSoftware: ...
> Nuke = NukeSoftware()  # I'm aware it would be more pythonic as NUKE but I find it looks a bit ugly with Qt
> 
> # init.py
> from vfxwindow import software
> if software.Nuke:  # Using bool will determine if it's the current software
>     from .nuke import NukeWindow as VFXWindow
> 
> # nuke.py
> >>> from vfxwindow.software import Nuke
> >>> self.software = Nuke
> >>> self.software
> 'Nuke'
> >>> self.software == 'nuke'  # case insensitive check
> True
> >>> self.software.batch  # hide away the batch mode attribute
> False
> >>> self.software.version  # gets the full version as a string
> '14.0v5'
> >>> int(self.software.version)  # gets the major version
> 14
> >>> float(self.software.version)  # gets the major and minor version
> 14.0
> ```
> 
> Also thanks, I've never quite known how to properly deprecate stuff. Since I'm using 2.0 as an excuse to do a major code cleanup, I'm planning on expanding the documentation a lot more then as I do that :)
> 
> (also don't worry about testing the Maya widget wrapping, I'll get round to doing it at some point)

So for now you're ok with that solution ? Keeping the legacy attributes and maybe replace them in the future (On a major update)

I also like the idea of software objects, they could be dataclasses actually, that would make sense for what they will be used for. But I think this may request some work, it could make sense for a future update.

I'm happy to help, actually this way of deprecating is really "documentation oriented". There's other way, like subclassing Warning or implementing special decorators with loggers. Nothing 100% formal tho. For a single attribute I think there's not real good way other than documentation.

So, what do you think about the PR, maybe you prefer if I remove every changes and leave this for a future update where you implement software classes ? (And I keep only the maya widget icon fix in this PR)

**Comment by huntfx** [comment]
> So for now you're ok with that solution ? Keeping the legacy attributes and maybe replace them in the future (On a major update)

Yeah absolutely, those attributes will 100% be nuked for 2.0, I'd mainly just not decided on `self.application` or `self.software` and you made the choice for me :)   And while I like the idea of dataclasses, I'm aiming to keep this compatible with py2 for a lot longer, so a custom one will work fine.

I'm happy with the PR as it stands anyway, will do what I did last time and get it slowly tested :)

**Comment by huntfx** [comment]
Hey, I've not forgotten about this, just been on holiday so not had a good chance to fully test yet :)

In regards to `pm.uitypes.toQtObject()`, behind the scenes its just calling `wrapinstance(maya.OpenMayaUI.MQtUtil.findControl(), QtCore.QObject)` (with some extra stuff to get the correct widget type), so it should be totally fine leaving this removed.

I've also started doing a bit on the application data class in a separate branch, with all the same behaviour as my previous example. I decided on using "application" rather than "software" after having a chat with some coworkers, though my branch is still far off merging so I'll just do a quick update on this PR to update that.

I also just went down all the other changes in a bit more detail - I'll test your edits to `_parentOverride`, ~~will think about if the change of `pm.uitypes.toQtControl` to `getMainWindow` should just directly call the underlying function~~, and fix where `pm.uitypes.toQtObject(form)` was changed to `mc.uitypes.toQtObject`.

**Comment by huntfx** [comment]
With the parent override part where added the part saying `If the window has no parent, it was probably forgotten by user so we can assume it should be the maya main window.`, were you able to cause this to happen at one point or you just spotted a potential issue with the code flow?

If I recreate it by doing this (the only way I could figure out how), then the main Maya window is moved when it should just be the widget itself.

```python
from vfxwindow.debug import TestWindow
TestWindow.WindowDockable = True
win = TestWindow.show()
win.setParent(None)
win.move(50, 50)
```

What works is changing `getMainWindow()` to `super(MayaWindow, self)._parentOverride()`, but I'd like to run it by you first in case you spotted something I didn't.

```python
if base is None:
    self.__parentTemp = super(MayaWindow, self)._parentOverride()
```

**Comment by gpijat** [comment]
> With the parent override part where added the part saying `If the window has no parent, it was probably forgotten by user so we can assume it should be the maya main window.`, were you able to cause this to happen at one point or you just spotted a potential issue with the code flow?
> 
> If I recreate it by doing this (the only way I could figure out how), then the main Maya window is moved when it should just be the widget itself.
> 
> ```python
> from vfxwindow.debug import TestWindow
> TestWindow.WindowDockable = True
> win = TestWindow.show()
> win.setParent(None)
> win.move(50, 50)
> ```
> 
> What works is changing `getMainWindow()` to `super(MayaWindow, self)._parentOverride()`, but I'd like to run it by you first in case you spotted something I didn't.
> 
> ```python
> if base is None:
>     self.__parentTemp = super(MayaWindow, self)._parentOverride()
> ```

Hey, I think during my tests I had a weird issue where the full maya window moved. Unfortunately now it's not that fresh in my mind.
It may also have been about the icon thing, when it's docked and undocked the behavior is a bit weird and if the widget is created with no parent and is in a floating mode at first show, I think there was something weird.

**Comment by huntfx** [comment]
Ok thanks, I think the edit I made should be fully safe anyway as it defaults to `self` if no parent is found. I tried docking/undocking the window a bunch of times but couldn't break anything.

More a note for myself but I also just noticed `setDocked` and `setFloating` don't work when the window is floating. It did previously though so shouldn't be too hard to track down the issue.

**Comment by huntfx** [comment]
I went digging into that dock/floating issue and opened a can of worms. Good news is it's improved a lot, though I found one or two edge cases I had to add comments for as I wasn't able to fix.

Anyway, I'll get this merged into the main branch now as your PR is stable and I shouldn't be doing edits lol, thanks again for the help. I'll get my application class branch merged in for 1.9 too as it'll let me fix a few messier bits of code.

**Pull request merged**
